{% set name = "range-v3" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ericniebler/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 015adb2300a98edfceaf0725beec3337f542af4915cec4d0b89fa0886f4ba9cb

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/meta  # [unix]
    - test -d ${PREFIX}/include/concepts  # [unix]
    - test -d ${PREFIX}/include/range  # [unix]
    - test -f ${PREFIX}/include/range/v3/range.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/range-v3/range-v3-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/range-v3/range-v3-config-version.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\range\v3\range.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\range-v3\range-v3-config.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\range-v3\range-v3-config-version.cmake (exit 1)  # [win]

about:
  home: https://github.com/ericniebler/range-v3
  summary: Range library for C++14/17/20, basis for C++20's std::ranges
  description: |
    Range library for C++14/17/20. This code was the basis of a formal 
    proposal to add range support to the C++ standard library. That 
    proposal evolved through a Technical Specification, and finally into 
    P0896R4 "The One Ranges Proposal" which was merged into the C++20 
    working drafts in November 2018.
  license: BSL-1.0 
  license_family: BSL
  license_file: LICENSE.txt
  doc_url: https://ericniebler.github.io/range-v3/
  dev_url: https://github.com/ericniebler/range-v3

extra:
  recipe-maintainers:
    - Wongboo
